
import { RouteEntry } from '@arikajs/router';

export class HtmlGenerator {
    public generate(routes: RouteEntry[], appName: string): string {
        const groups = this.groupByPrefix(routes);
        const groupHtml = Object.entries(groups).map(([name, groupRoutes]) => this.renderGroup(name, groupRoutes)).join('');

        return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${appName} API Documentation</title>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;600;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --primary: #8b5cf6;
            --bg: #f8fafc;
            --card: #ffffff;
            --text-main: #0f172a;
            --text-muted: #64748b;
            --border: #e2e8f0;
            --get: #10b981;
            --post: #3b82f6;
            --put: #f59e0b;
            --delete: #ef4444;
        }

        * { margin:0; padding:0; box-sizing:border-box; }
        body { font-family: 'Plus Jakarta Sans', sans-serif; background: var(--bg); color: var(--text-main); line-height: 1.6; }
        .container { max-width: 1000px; margin: 0 auto; padding: 4rem 2rem; }
        header { margin-bottom: 4rem; }
        h1 { font-size: 2.5rem; margin-bottom: 0.5rem; }
        .badge { display: inline-block; padding: 0.25rem 0.75rem; background: var(--primary); color: white; border-radius: 99px; font-size: 0.8rem; font-weight: 600; }
        
        .group { margin-bottom: 3rem; }
        .group-title { font-size: 1.5rem; margin-bottom: 1.5rem; border-bottom: 2px solid var(--border); padding-bottom: 0.5rem; text-transform: capitalize; }
        
        .route-card { background: var(--card); border: 1px solid var(--border); border-radius: 12px; padding: 1.5rem; margin-bottom: 1rem; transition: transform 0.2s; }
        .route-card:hover { transform: translateY(-2px); box-shadow: 0 10px 20px rgba(0,0,0,0.05); }
        
        .route-header { display: flex; align-items: center; gap: 1rem; margin-bottom: 1rem; }
        .method { padding: 0.25rem 0.75rem; border-radius: 6px; font-weight: 700; font-size: 0.8rem; min-width: 70px; text-align: center; color: white; }
        .method.GET { background: var(--get); }
        .method.POST { background: var(--post); }
        .method.PUT { background: var(--put); }
        .method.DELETE { background: var(--delete); }
        .path { font-family: monospace; font-size: 1.1rem; font-weight: 600; color: var(--text-main); }
        
        .route-info { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; font-size: 0.9rem; }
        .label { color: var(--text-muted); font-weight: 600; margin-bottom: 0.25rem; }
        .value { color: var(--text-main); }
        
        .middleware-tag { display: inline-block; padding: 0.1rem 0.5rem; background: #f1f5f9; border: 1px solid var(--border); border-radius: 4px; font-size: 0.75rem; margin-right: 0.25rem; }
        
        footer { text-align: center; margin-top: 4rem; color: var(--text-muted); font-size: 0.8rem; }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <div class="badge">ArikaJS Docs</div>
            <h1>${appName}</h1>
            <p>API documentation generated on ${new Date().toLocaleDateString()}</p>
        </header>

        ${groupHtml}

        <footer>
            Generated by @arikajs/docs &copy; 2026
        </footer>
    </div>
</body>
</html>`;
    }

    private renderGroup(name: string, routes: RouteEntry[]): string {
        const routesHtml = routes.map(route => `
            <div class="route-card">
                <div class="route-header">
                    <span class="method ${route.method}">${route.method}</span>
                    <span class="path">${route.path}</span>
                </div>
                <div class="route-info">
                    <div>
                        <div class="label">Route Name</div>
                        <div class="value">${route.name || '-'}</div>
                    </div>
                    <div>
                        <div class="label">Middleware</div>
                        <div class="value">
                            ${route.middleware.map(m => `<span class="middleware-tag">${typeof m === 'string' ? m : m.name || 'Closure'}</span>`).join('') || '-'}
                        </div>
                    </div>
                </div>
            </div>
        `).join('');

        return `
            <div class="group">
                <h2 class="group-title">${name.replace('/', '')}</h2>
                ${routesHtml}
            </div>
        `;
    }

    private groupByPrefix(routes: RouteEntry[]): Record<string, RouteEntry[]> {
        const groups: Record<string, RouteEntry[]> = {};
        routes.forEach(route => {
            const group = route.prefix || 'General';
            if (!groups[group]) groups[group] = [];
            groups[group].push(route);
        });
        return groups;
    }
}
